### ISSUE TITLE
Large or small manipulator manifolds?

### ISSUE THREAD

**Issue by tom-f-oconnell** [FlySorterLLC/MAPLEHardware#2]
I couldn't find any reference indicating whether it matters if either the organism or object manipulator manifold is made from [`Drawings/LargeManipulatorManifold.PDF`](https://github.com/FlySorterLLC/MAPLEHardware/blob/master/Drawings/LargeManipulatorManifold.PDF) or from [`Drawings/SmallManipulatorManifold.PDF`](https://github.com/FlySorterLLC/MAPLEHardware/blob/master/Drawings/SmallManipulatorManifold.PDF).

In the image on the page numbered 22 in the instructions, it seems that the object manipulator manifold is the larger size, and the organism manipulator manifold is the smaller one.

Does it matter?  If it does matter, could you guys also export an STL for the larger size (I don't have a copy of SolidWorks myself)?  Right now, it seems there is only `SmallManipulatorManifold.STL` in the STL directory, and I was going to try to 3D print these parts.

**Comment by flysorter** [comment]
Hi Tom - the fly manipulator should be made from the SmallManipulatorManifold and the object manipulator from the LargeManipulatorManifold. The fly manipulator mounts to a shoulder screw and pivots, which allows the robot to detect collisions. Since there is a suction cup with bellows on the object manipulator, there is more tolerance for Z height errors.

I will upload an STL for the large manifold (which we'd fabricated from aluminum for our robot, hence no STL).
